//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.PowerTools.OptionsPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.PowerTools.OptionsPage.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show matches in the editor.
        /// </summary>
        internal static string AdornmentMatch {
            get {
                return ResourceManager.GetString("AdornmentMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control click shows definitions in Peek.
        /// </summary>
        internal static string ControlClickOpensPeek {
            get {
                return ResourceManager.GetString("ControlClickOpensPeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control click options.
        /// </summary>
        internal static string ControlClickOptions {
            get {
                return ResourceManager.GetString("ControlClickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show matches in the margin.
        /// </summary>
        internal static string MarginMatch {
            get {
                return ResourceManager.GetString("MarginMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match margin options.
        /// </summary>
        internal static string MatchMarginOptions {
            get {
                return ResourceManager.GetString("MatchMarginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a separator between methods in the editor.
        /// </summary>
        internal static string MethodSeparatorEnabled {
            get {
                return ResourceManager.GetString("MethodSeparatorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show code structure in the editor.
        /// </summary>
        internal static string StructureAdornmentEnabled {
            get {
                return ResourceManager.GetString("StructureAdornmentEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show code structure in the margin.
        /// </summary>
        internal static string StructureMarginEnabled {
            get {
                return ResourceManager.GetString("StructureMarginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the code structure preview in the margin.
        /// </summary>
        internal static string StructurePreviewEnabled {
            get {
                return ResourceManager.GetString("StructurePreviewEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure visualizer options.
        /// </summary>
        internal static string StructureVisualizerOptions {
            get {
                return ResourceManager.GetString("StructureVisualizerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress blank lines.
        /// </summary>
        internal static string SyntacticFisheyeCompressBlankLines {
            get {
                return ResourceManager.GetString("SyntacticFisheyeCompressBlankLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress lines that do not have any alphanumeric characters.
        /// </summary>
        internal static string SyntacticFisheyeCompressSimpleLines {
            get {
                return ResourceManager.GetString("SyntacticFisheyeCompressSimpleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntactic line compression options.
        /// </summary>
        internal static string SyntacticFisheyeOptions {
            get {
                return ResourceManager.GetString("SyntacticFisheyeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time stamps in debug output.
        /// </summary>
        internal static string TimeStampMarginEnabled {
            get {
                return ResourceManager.GetString("TimeStampMarginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time stamp margin options.
        /// </summary>
        internal static string TimeStampMarginOptions {
            get {
                return ResourceManager.GetString("TimeStampMarginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hours in the time stamp margin.
        /// </summary>
        internal static string TimeStampMarginShowHours {
            get {
                return ResourceManager.GetString("TimeStampMarginShowHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show milliseconds in the time stamp margin.
        /// </summary>
        internal static string TimeStampMarginShowMilliseconds {
            get {
                return ResourceManager.GetString("TimeStampMarginShowMilliseconds", resourceCulture);
            }
        }
    }
}
